services:
  redis:
    image: redis:7
    ports:
      - "6379:6379"
    volumes:
      - ./redis-data:/data
    command: redis-server --maxmemory 2.5gb --maxmemory-policy allkeys-lru --appendonly yes
    restart: always